### ISSUE TITLE
The Descent and Now & Then

### ISSUE THREAD

**Issue by kweerious** [matthewfdaniels/scripts#1]
In your article, The Descent (a horror/action movie) is missing from those filtered sets, as is Now & Then. Just notable that some of the movies with a high amount of female coded dialogue seems to not show up in the smaller filtered sets. It also breaks the bottom set.

Is it because they have 100%?

**Comment by matthewfdaniels** [comment]
Looks good to me. Do you have one of the genre filters on?

![screen shot 2016-04-07 at 6 11 44 pm](https://cloud.githubusercontent.com/assets/2880174/14368523/3d8e041e-fcec-11e5-80a1-7a1aac780234.png)

**Comment by kweerious** [comment]
I had the bottom display filter on. It should have 8 movies. Missing from the list are The Descent and Now & Then. They also don't come up except in the unfiltered view with the dots.

**Comment by matthewfdaniels** [comment]
So just fixed a bug that was excluding 100% female dialogue from the last chart. Thanks for finding that!

The site is updated now and hopefully you can see those films.

The reason why Descent is not in the spectrum chart at the top (single-bar) is because it didn't gross high enough to be in that chart (which only shows films that are >$45M inflation-adjusted)
